language: go
sudo: required
install: true
os:
  - linux
  - osx
go:
  - 1.7.4
  - 1.8
  - master
env:
  matrix:
    - GOARCH=amd64
    - GOARCH=386
before_install:
  - '[[ $TRAVIS_OS_NAME == "linux" ]] && sudo sysctl -w net.ipv6.conf.all.disable_ipv6=0 || true'
  - '[[ $TRAVIS_OS_NAME == "linux" ]] && sudo sysctl -w net.ipv6.conf.lo.disable_ipv6=0 || true'
script:
  - ./go.test.bash
  - '[[ $TRAVIS_GO_VERSION == "1.8" ]] && ./check-fmt.sh || true'
services:
  - redis
  - mongodb
matrix:
  allow_failures:
    - go: master
after_success:
  - bash <(curl -s https://codecov.io/bash)
