language: go
sudo: required
install: true
os:
  - linux
go:
  - 1.8
env:
  global:
    - GO_FOR_RELEASE=1.8
  matrix:
    - GOARCH=amd64
before_install:
  - '[[ $TRAVIS_OS_NAME == "linux" ]] && sudo sysctl -w net.ipv6.conf.all.disable_ipv6=0 || true'
  - '[[ $TRAVIS_OS_NAME == "linux" ]] && sudo sysctl -w net.ipv6.conf.lo.disable_ipv6=0 || true'
script:
  - echo "tested"
services:
  - redis
  - mongodb
matrix:
  allow_failures:
    - go: master
after_success:
  - test -n "$TRAVIS_TAG" && curl -sL https://raw.githubusercontent.com/morpheu/push-to-packagecloud/master/push.sh | GORELEASE_PACKAGE_NAME=tsuru PACKAGE_NAME=tsuru bash -x

