language: go
sudo: required
install: true
os:
  - linux
go:
  - 1.8
env:
  global:
    - GO_FOR_RELEASE=1.8
  matrix:
    - GOARCH=amd64
before_install:
  - '[[ $TRAVIS_OS_NAME == "linux" ]] && sudo sysctl -w net.ipv6.conf.all.disable_ipv6=0 || true'
  - '[[ $TRAVIS_OS_NAME == "linux" ]] && sudo sysctl -w net.ipv6.conf.lo.disable_ipv6=0 || true'
script:
  - ./go.test.bash
  - '[[ $TRAVIS_GO_VERSION == "1.8" ]] && ./check-fmt.sh || true'
services:
  - redis
  - mongodb
matrix:
  allow_failures:
    - go: master
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - test -n "$TRAVIS_TAG" && curl -sL https://raw.githubusercontent.com/morpheu/push-to-packagecloud/master/push.sh | PACKAGE_NAME=tsuru-client bash
